apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: voting-project
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:6-alpine
    ports:
    - containerPort: 6379
