apiVersion: v1
kind: Pod
metadata:
  name: voting-app
  namespace: voting-project
  labels:
    app: voting
spec:
  containers:
  - name: voting-app
    image: dockersamples/examplevotingapp_vote:latest
    ports:
      - containerPort: 80
    env:
      - name: REDIS_HOST
        value: "redis.voting-project.svc.cluster.local"
      - name: REDIS_PORT
        value: "6379"
