apiVersion: v1
kind: Pod
metadata:
  name: worker
  namespace: voting-project
  labels:
    app: worker
spec:
  containers:
  - name: worker
    image: dockersamples/examplevotingapp_worker:latest
    env:
      - name: REDIS_HOST
        value: "redis.voting-project.svc.cluster.local"
      - name: REDIS_PORT
        value: "6379"
      - name: POSTGRES_HOST
        value: "postgres.voting-project.svc.cluster.local"
      - name: POSTGRES_PORT
        value: "5432"
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_USER
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_PASSWORD
      - name: POSTGRES_DB
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: POSTGRES_DB
    ports:
      - containerPort: 80
