apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: voting-project
type: Opaque
data:
  # Example base64 values (replace with secure values). 
  # POSTGRES_PASSWORD: echo -n 'mysecretpassword' | base64
  POSTGRES_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_DB: dm90aW5n
